version: "3.8"

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
    - 81:8080